#!/bin/bash

# test suite for counter files, tests each program with
# certain numbers of threads, it assumes you are in the
# Project3/code directory
# can be run by using the following command (no arguments):
#
# ./testSuite.sh

# this can probably be implemented more efficiently, but I have no idea 
# how bash scripting works
# tip: can use ": '" and "'" to open and close multiline bash comments



clear
echo "-------------------------------------------------------------"
echo "----------------TEST SUITE FOR COUNTER PROGRAMS--------------"
echo "-------------------------------------------------------------"
echo
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "RUNNING PROGRAMS WITH LARGER AMOUNTS OF THREADS MAY RESULT IN LONGER RUNTIMES"
echo
echo "RUNTIMES ARE ILAB SERVER DEPENDENT, AND WILL DIFFER ON EACH RUN"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"



make clean
make

rm results.org
touch results.org

programs=("naive_counter" "naive_counter_plus" "atomic_counter" "scalable_counter")
# programs=("naive_counter" "naive_counter_plus")
# test counter programs with the following numbers of threads
testSuite=(1 2 4 8 16 32 64 128)
# testSuite=(1 2 4 8)
# tests represents the number of times you are to run each test
tests=1


for val in ${programs[@]}; do
        echo
        echo "-----------------------$val---------------------------"
        echo
        echo "#+PLOT: title:\"$val\" ind:1 type:2d file:\"./img/${val}.png\"  set:\"xlabel 'threads'\" set:\"ylabel 'runtime'\" " >> results.org
        echo "| threadCount | runTime |" >> results.org
        echo 
        for i in ${testSuite[@]}; do
            echo "------------Test: NC" $i "-----------"
            echo
            for (( j=1;j<=tests;j++)) do
                echo "Test:" $j
                echo "./$val" ${i}
                ./${val} $i
                echo
            done
            done
                echo >> results.org
                echo "[[./img/$val.png]]" >> results.org
                echo >> results.org
                echo >> results.org
        done
        
